package universalcore.libs;

import cpw.mods.fml.common.Mod.Metadata;
import cpw.mods.fml.common.ModMetadata;

public class MCMod {

    @Metadata
    public static ModMetadata metadata;

    public static void MetaMcMod(){

        metadata.autogenerated = false;
        metadata.authorList.add("The UniversalTeam");
        metadata.credits = "Created by UniversalRed and the UniversalTeam";
        metadata.description = "The Basic, Fundamental Mod That supports Our Other Mods";
    }
}
